# Diversity in the film industry: data cleaning - Movie scripts

## Importing libraries and dataset

*Demographics* contains information on film, actor, character, gender, race, and number of words and sentences.

In [50]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np

In [53]:
script = pd.read_csv('./data/actor-metrics.csv')
script.drop('imdb', axis=1, inplace=True)

In [54]:
script.head()

,year,film,actor,characters,gender,race,race_simple,words,sentences
0,1989,born-on-the-fourth-of-july,Dale Dye,COLONEL,male,White/Caucasian,White,216.0,15.0
1,1989,born-on-the-fourth-of-july,David Warshofsky,LIEUTENANT,male,White/Caucasian,White,290.0,40.0
2,1989,born-on-the-fourth-of-july,Frank Whaley,TIMMY,male,White/Caucasian,White,104.0,14.0
3,1989,born-on-the-fourth-of-july,Jerry Levine,STEVE,male,White/Caucasian,White,300.0,35.0
4,1989,born-on-the-fourth-of-july,John F. Kennedy,KENNEDY,male,White/Caucasian,White,217.0,5.0

## 2. Analysis of the cast

For gender (male vs female) and race (white vs POC), in this section I obtain 3 dataframes with the percentage of cast by movie, year and total.

### 2.1. Cast by gender

In [60]:
film_cast_gender = dict(script.groupby('film').gender.value_counts(normalize=True))
year_cast_gender = dict(script.groupby('year').gender.value_counts(normalize=True))
total_cast_gender = dict(script.gender.value_counts(normalize=True))

In [56]:
# film
film_cast_gender_df = pd.DataFrame({'film': [],
              'gender': [],
            'cast_perc_gender': []})
film_cast_gender_df['film'] = [k[0] for k in film_cast_gender.keys()]
film_cast_gender_df['gender'] = [k[1] for k in film_cast_gender.keys()]
film_cast_gender_df['cast_perc_gender'] = film_cast_gender.values()

# year
year_cast_gender_df = pd.DataFrame({'year': [],
              'gender': [],
            'cast_perc_gender': []})
year_cast_gender_df['year'] = [k[0] for k in year_cast_gender.keys()]
year_cast_gender_df['gender'] = [k[1] for k in year_cast_gender.keys()]
year_cast_gender_df['cast_perc_gender'] = year_cast_gender.values()

# total
total_cast_gender_df = pd.DataFrame({'gender': [],
            'cast_perc_gender': []})
total_cast_gender_df['gender'] = total_cast_gender.keys()
total_cast_gender_df['cast_perc_gender'] = total_cast_gender.values()

### 2.2. Cast by race

In [63]:
film_cast_race_simple = dict(script.groupby('film').race_simple.value_counts(normalize=True))
year_cast_race_simple = dict(script.groupby('year').race_simple.value_counts(normalize=True))
total_cast_race_simple = dict(script.race_simple.value_counts(normalize=True))

In [64]:
# film
film_cast_race_df = pd.DataFrame({'film': [],
              'race_simple': [],
            'cast_perc_race': []})
film_cast_race_df['film'] = [k[0] for k in film_cast_race_simple.keys()]
film_cast_race_df['race_simple'] = [k[1] for k in film_cast_race_simple.keys()]
film_cast_race_df['cast_perc_race'] = film_cast_race_simple.values()

# year
year_cast_race_df = pd.DataFrame({'year': [],
              'race_simple': [],
            'cast_perc_race': []})
year_cast_race_df['year'] = [k[0] for k in year_cast_race_simple.keys()]
year_cast_race_df['race_simple'] = [k[1] for k in year_cast_race_simple.keys()]
year_cast_race_df['cast_perc_race'] = year_cast_race_simple.values()

# total
total_cast_race_df = pd.DataFrame({'race_simple': [],
            'cast_perc_race': []})
total_cast_race_df['race_simple'] = total_cast_race_simple.keys()
total_cast_race_df['cast_perc_race'] = total_cast_race_simple.values()

## 3. Analysis of the script

For gender (male vs female) and race (white vs POC), in this section I obtain 3 dataframes with the percentage of sentences said by characters who speak for than 100 words, by movie, year and total.

### 3.1. Gender and race script in absolute value by film/year/total

In [67]:
# films by gender
film_gender = script.groupby(['year','film', 'gender'], as_index=False).agg({'words': 'sum',
                                              'sentences': 'sum'})
# films by race
film_race = script.groupby(['year','film', 'race_simple'], as_index=False).agg({'words': 'sum',
                                              'sentences': 'sum'})
# years by gender
year_gender = script.groupby(['year', 'gender'], as_index=False).agg({'words': 'sum',
                                              'sentences': 'sum'})
# years by race
year_race = script.groupby(['year', 'race_simple'], as_index=False).agg({'words': 'sum',
                                              'sentences': 'sum'})
# total by gender
total_gender = script.groupby(['gender'], as_index=False).agg({'words': 'sum',
                                              'sentences': 'sum'})
# total by race
total_race = script.groupby(['race_simple'], as_index=False).agg({'words': 'sum',
                                                                  'sentences': 'sum'})

### 3.2. Gender and race in percentage by film/year/total

#### 3.2.1. Get dictionnaire with total count of words and sentences by film/year/total

In [35]:
# films
film_words = dict(script.groupby('film').words.sum())
film_sentences = dict(script.groupby('film').sentences.sum())

# years
year_words = dict(script.groupby('year').words.sum())
year_sentences = dict(script.groupby('year').sentences.sum())

# total
total_words = script.words.sum()
total_sentences = script.sentences.sum()

#### 3.2.2. Match values in dictionnaire with dataframes

In [70]:
# films
film_gender['total_words'] = film_gender.film.map(film_words)
film_gender['total_sentences'] = film_gender.film.map(film_sentences)
film_race['total_words'] = film_race.film.map(film_words)
film_race['total_sentences'] = film_race.film.map(film_sentences)

# years
year_gender['total_words'] = year_gender.year.map(year_words)
year_gender['total_sentences'] = year_gender.year.map(year_sentences)
year_race['total_words'] = year_race.year.map(year_words)
year_race['total_sentences'] = year_race.year.map(year_sentences)

# totals
total_gender['total_words'] = total_words
total_gender['total_sentences'] = total_sentences
total_race['total_words'] = total_words
total_race['total_sentences'] = total_sentences

#### 3.3.3. Adding new columns with percentage

In [72]:
lst= [film_gender, film_race, year_gender, year_race, total_gender, total_race]

# words
for i in lst:
    i['words_perc'] = i.words / i.total_words * 100
    
# percentage
for i in lst:
    i['sentences_perc'] = i.sentences / i.total_sentences * 100

In [73]:
film_race

,year,film,race_simple,words,sentences,total_words,total_sentences,words_perc,sentences_perc
0,1989,born-on-the-fourth-of-july,POC,208.0,15.0,5151.0,620.0,4.038051,2.419355
1,1989,born-on-the-fourth-of-july,White,4943.0,605.0,5151.0,620.0,95.961949,97.580645
2,1989,dead-poets-society,White,5217.0,1289.0,5217.0,1289.0,100.000000,100.000000
3,1989,driving-miss-daisy,POC,3531.0,544.0,9675.0,1520.0,36.496124,35.789474
4,1989,driving-miss-daisy,White,6144.0,976.0,9675.0,1520.0,63.503876,64.210526
5,1989,field-of-dreams,POC,1369.0,207.0,8933.0,1299.0,15.325199,15.935335
6,1989,field-of-dreams,White,7564.0,1092.0,8933.0,1299.0,84.674801,84.064665
7,1989,my-left-foot,White,4749.0,980.0,4749.0,980.0,100.000000,100.000000
8,2015,bridge-of-spies,White,9915.0,1351.0,9915.0,1351.0,100.000000,100.000000
9,2015,brooklyn,White,10591.0,1469.0,10591.0,1469.0,100.000000,100.000000
10,2015,mad-max,POC,320.0,64.0,3130.0,694.0,10.223642,9.221902
11,2015,mad-max,White,2810.0,630.0,3130.0,694.0,89.776358,90.778098
12,2015,room,POC,616.0,92.0,8373.0,1414.0,7.356981,6.506365
13,2015,room,White,7757.0,1322.0,8373.0,1414.0,92.643019,93.493635
14,2015,spotlight,White,13113.0,1975.0,13113.0,1975.0,100.000000,100.000000
15,2015,the-big-short,POC,515.0,71.0,13241.0,1782.0,3.889434,3.984287
16,2015,the-big-short,White,12726.0,1711.0,13241.0,1782.0,96.110566,96.015713
17,2015,the-martian,POC,2589.0,365.0,10550.0,1507.0,24.540284,24.220305
18,2015,the-martian,White,7961.0,1142.0,10550.0,1507.0,75.459716,75.779695
19,2015,the-revenant,White,4005.0,549.0,4005.0,549.0,100.000000,100.000000
20,2017,call-me-by-your-name,White,6673.0,1048.0,6673.0,1048.0,100.000000,100.000000
21,2017,darkest-hour,POC,147.0,27.0,8034.0,1077.0,1.829724,2.506964
22,2017,darkest-hour,White,7887.0,1050.0,8034.0,1077.0,98.170276,97.493036
23,2017,dunkirk,White,2353.0,446.0,2353.0,446.0,100.000000,100.000000
24,2017,get-out,POC,3309.0,653.0,7094.0,1330.0,46.645052,49.097744
25,2017,get-out,White,3785.0,677.0,7094.0,1330.0,53.354948,50.902256
26,2017,lady-bird,POC,292.0,49.0,7664.0,1148.0,3.810021,4.268293
27,2017,lady-bird,White,7372.0,1099.0,7664.0,1148.0,96.189979,95.731707
28,2017,phantom-thread,White,5541.0,783.0,5541.0,783.0,100.000000,100.000000
29,2017,the-post,POC,175.0,13.0,11135.0,1528.0,1.571621,0.850785
30,2017,the-post,White,10960.0,1515.0,11135.0,1528.0,98.428379,99.149215
31,2017,the-shape-of-water,POC,1319.0,201.0,8036.0,1347.0,16.413639,14.922049
32,2017,the-shape-of-water,White,6717.0,1146.0,8036.0,1347.0,83.586361,85.077951
33,2017,three-billboards-outside-ebbing-missouri,POC,782.0,76.0,9480.0,1195.0,8.248945,6.359833
34,2017,three-billboards-outside-ebbing-missouri,White,8698.0,1119.0,9480.0,1195.0,91.751055,93.640167

## 4. Creating final dataframe with % of cast and % of script by gender and race

### 4.1. Gender

In [86]:
film_gender_clean = pd.merge(film_gender, film_cast_gender_df, how='inner', on=['film', 'gender'])
film_gender_clean['cast_perc_gender'] = film_gender_clean['cast_perc_gender']*100

In [87]:
year_gender_clean = pd.merge(year_gender, year_cast_gender_df, how='inner', on=['year', 'gender'])
year_gender_clean['cast_perc_gender'] = year_gender_clean['cast_perc_gender']*100

In [88]:
total_gender_clean = pd.merge(total_gender, total_cast_gender_df, how='inner', on=['gender'])
total_gender_clean['cast_perc_gender'] = total_gender_clean['cast_perc_gender']*100

### 4.2. Race

In [89]:
film_race_clean = pd.merge(film_race, film_cast_race_df, how='inner', on=['film', 'race_simple'])
film_race_clean['cast_perc_race'] = film_race_clean['cast_perc_race']*100

In [90]:
year_race_clean = pd.merge(year_race, year_cast_race_df, how='inner', on=['year', 'race_simple'])
year_race_clean['cast_perc_race'] = year_race_clean['cast_perc_race']*100

In [91]:
total_race_clean = pd.merge(total_race, total_cast_race_df, how='inner', on=['race_simple'])
total_race_clean['cast_perc_race'] = total_race_clean['cast_perc_race']*100

## 5. Exporting final datasets

In [94]:
# script
film_gender_clean.to_csv("./data/script/film_gender_clean.csv")
year_gender_clean.to_csv("./data/script/year_gender_clean.csv")
total_gender_clean.to_csv("./data/script/total_gender_clean.csv")
film_race_clean.to_csv("./data/script/film_race_clean.csv")
year_race_clean.to_csv("./data/script/year_race_clean.csv")
total_race_clean.to_csv("./data/script/total_race_clean.csv")